// Zigbee
const SET_PRODUCTID = 'SET_PRODUCTID'
const SET_SERIALPORT = 'SET_SERIALPORT'
const SET_ZIGBEECONNECT = 'SET_CONNECT'

// Entity

const ADD_ENTITY = 'ADD_ENTITY'

// mqtt

const SET_MQTTSERVER = 'SET_MQTTSERVER'
const SET_MQTTCLIENT = 'SET_MQTTCLIENT'
const SET_MQTTCONNECT = 'SET_CONNECT'

// Auth

const SET_AUTH_SERVICES = 'SET_AUTH_SERVICES',
      SET_AUTH_TOKEN = 'SET_AUTH_TOKEN'

// Meter
const SET_METER_INFO = 'SET_METER_INFO'

module.exports = {
  SET_PRODUCTID,
  SET_SERIALPORT,
  SET_MQTTCONNECT,
  SET_ZIGBEECONNECT,
  SET_AUTH_SERVICES,
  SET_AUTH_TOKEN,
  SET_MQTTCLIENT,
  SET_MQTTSERVER,
  SET_METER_INFO
}
